blueprint:
  name: "Zooz ZEN37 Control: Refined Dimming, Temp & 9-Color Cycle"
  description: "Advanced control for Zooz ZEN37 (Z-Wave JS). Features min/max brightness limiting, smooth continuous dimming/temp control, and a graphical 9-color cycle."
  domain: automation

  input:
    # --- Core Devices & Helpers ---
    zwave_device:
      name: Zooz ZEN37 Remote
      description: Select your Zooz ZEN37 device (Z-Wave JS)
      selector:
        device:
          multiple: false
          filter:
            - integration: zwave_js
              manufacturer: Zooz

    targets:
      name: Light/Switch Entities
      description: Choose one or more Light/Switch Entities you want to control
      selector:
        entity:
          filter:
            - domain:
                - light
                - switch
          multiple: true

    color_cycle_index:
      name: Color Cycle Index Helper (input_number)
      description: Choose the Input Number Helper to store the color cycle index (0..N)
      selector:
        entity:
          multiple: false
          filter:
            - domain:
                - input_number

    # --- Hold Actions (Restored) ---
    arrow_left_hold:
      name: Button 3 (Bottom Left) Hold Release Action
      description: Action to execute when Button 3 is released after a hold.
      default: []
      selector:
        action: {}

    arrow_right_hold:
      name: Button 4 (Bottom Right) Hold Release Action
      description: Action to execute when Button 4 is released after a hold.
      default: []
      selector:
        action: {}

    # --- Color & Brightness Limits ---
    min_brightness_pct:
      name: Minimum Brightness (%)
      description: The minimum brightness level (in percent) when dimming down.
      default: 1
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider
          
    max_brightness_pct:
      name: Maximum Brightness (%)
      description: The maximum brightness level (in percent) when dimming up.
      default: 100
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider
          
    min_color_temp_kelvin:
      name: Minimum Color Temperature (Kelvin - Warmer)
      description: The warmest color temperature limit (e.g., 2000K).
      default: 2000
      selector:
        number:
          min: 1000
          max: 6500
          step: 100
          mode: slider

    max_color_temp_kelvin:
      name: Maximum Color Temperature (Kelvin - Cooler)
      description: The coolest color temperature limit (e.g., 6500K).
      default: 4700
      selector:
        number:
          min: 1000
          max: 6500
          step: 100
          mode: slider

    # --- Color Cycle List ---
    color_0:
      name: Color 0 (Default White)
      default: [255, 255, 255]
      selector:
        color_rgb:
    color_1:
      name: Color 1
      default: [255, 255, 0]
      selector:
        color_rgb:
    color_2:
      name: Color 2
      default: [255, 165, 0]
      selector:
        color_rgb:
    color_3:
      name: Color 3
      default: [255, 0, 0]
      selector:
        color_rgb:
    color_4:
      name: Color 4
      default: [255, 0, 123]
      selector:
        color_rgb:
    color_5:
      name: Color 5
      default: [153, 0, 255]
      selector:
        color_rgb:
    color_6:
      name: Color 6
      default: [0, 30, 255]
      selector:
        color_rgb:
    color_7:
      name: Color 7
      default: [0, 85, 128]
      selector:
        color_rgb:
    color_8:
      name: Color 8
      default: [0, 255, 42]
      selector:
        color_rgb:
          
    # --- Timing & Step Settings ---
    repeat_delay:
      name: Delay for brightness step (ms)
      default: 50
      selector:
        number:
          min: 20
          max: 1000
          step: 10
          mode: slider

    brightness_step_pct:
      name: Brightness Level step for each iteration (%)
      default: 20
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider
      
    color_temp_delay_input:
      name: Delay for color temp step (ms)
      default: 50
      selector:
        number:
          min: 20
          max: 1000
          step: 10
          mode: slider

    color_temp_step_kelvin_input:
      name: Color Temperature step (Kelvin)
      default: 300
      selector:
        number:
          min: 10
          max: 500
          step: 10
          mode: slider

mode: restart

# --- Z-Wave JS Triggers ---
# Note on Z-Wave JS Central Scene Values:
# 0 = Key Pressed (Single Tap)
# 1 = Key Released
# 2 = Key Held Down
trigger:
  # Button 1 (Top Left) - ON / UP
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: !input zwave_device
      property_key_name: "Scene 001"
      value: 0 # Key Pressed
    id: "on"
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: !input zwave_device
      property_key_name: "Scene 001"
      value: 2 # Key Held Down
    id: "brightness_move_up"
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: !input zwave_device
      property_key_name: "Scene 001"
      value: 1 # Key Released
    id: "brightness_stop"

  # Button 2 (Top Right) - OFF / DOWN
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: !input zwave_device
      property_key_name: "Scene 002"
      value: 0 # Key Pressed
    id: "off"
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: !input zwave_device
      property_key_name: "Scene 002"
      value: 2 # Key Held Down
    id: "brightness_move_down"
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: !input zwave_device
      property_key_name: "Scene 002"
      value: 1 # Key Released
    id: "brightness_stop"

  # Button 3 (Bottom Left) - PREV COLOR / COOLER
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: !input zwave_device
      property_key_name: "Scene 003"
      value: 0 # Key Pressed
    id: "arrow_left_click"
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: !input zwave_device
      property_key_name: "Scene 003"
      value: 2 # Key Held Down
    id: "arrow_left_hold"
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: !input zwave_device
      property_key_name: "Scene 003"
      value: 1 # Key Released
    id: "arrow_left_release"

  # Button 4 (Bottom Right) - NEXT COLOR / WARMER
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: !input zwave_device
      property_key_name: "Scene 004"
      value: 0 # Key Pressed
    id: "arrow_right_click"
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: !input zwave_device
      property_key_name: "Scene 004"
      value: 2 # Key Held Down
    id: "arrow_right_hold"
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: !input zwave_device
      property_key_name: "Scene 004"
      value: 1 # Key Released
    id: "arrow_right_release"

action:
  - variables:
      target_entities: !input targets
      lights: >
        {{ expand(target_entities) | map(attribute='entity_id') | select('match', '^light\.') | list }}
      switches: >
        {{ expand(target_entities) | map(attribute='entity_id') | select('match', '^switch\.') | list }}
          
      # Brightness
      repeat_delay: !input repeat_delay
      brightness_step_pct: !input brightness_step_pct
      min_brightness_pct: !input min_brightness_pct
      max_brightness_pct: !input max_brightness_pct
      
      # Temperature
      color_temp_delay: !input color_
